name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Build package
      run: poetry build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.os }}-${{ github.ref_name }}
        path: dist/

  publish:
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - name: Download artifacts for Ubuntu
      uses: actions/download-artifact@v2
      with:
        name: build-ubuntu-22.04-${{ github.ref_name }}
        path: dist/

    - name: Download artifacts for Windows
      uses: actions/download-artifact@v2
      with:
        name: build-windows-2022-${{ github.ref_name }}
        path: dist/

    - name: Download artifacts for macOS
      uses: actions/download-artifact@v2
      with:
        name: build-macos-12-${{ github.ref_name }}
        path: dist/

    - name: Publish Ubuntu artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_directory: dist

    - name: Publish Windows artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_directory: dist

    - name: Publish macOS artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_directory: dist
