name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Build package
      run: poetry build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ github.ref_name }}
        path: dist/

  publish:
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-${{ github.ref_name }}
        path: dist/

    - name: Publish artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_directory: dist

